Repository stonepillars/goon-flock, pull requests merged in 2022-03, with the labels that each got.

#15 Fixes #9 - Sentinel no longer runtimes, also efficiency fix, also no targetting ghosts fix
  code/obj/flock/structure/sentinel.dm
Labels: size/XS

#23 Drones now drop their resources when diffracted
  code/mob/living/critter/flock/flockdrone.dm
Labels: bug, size/XS

#24 Slight tweaks to flockdrone AI to prioritise building material deposits and conversion of walls/doors/closets
  code/mob/living/critter/ai/flock/flockdrone.dm
  code/mob/living/critter/ai/flock/flocktasks.dm
Labels: size/L

#20 Flockpanel TGUI
  browserassets/tgui/tgui.bundle.css
  browserassets/tgui/tgui.bundle.js
  code/datums/abilities/flock/flockmind.dm
  code/datums/flock/flock.dm
  code/datums/flock/flockpanel.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/intangible/flock/flockmind.dm
  code/modules/admin/debug.dm
  code/obj/flock/structure/flock_structure_parent.dm
  goonstation.dme
  tgui/packages/tgui/index.js
  tgui/packages/tgui/interfaces/FlockPanel.js
  tgui/packages/tgui/styles/themes/flock.scss
Labels: tgui, QoL, size/XL

#29 All flockdrone tasks now have icons
  browserassets/tgui/tgui.bundle.js
  tgui/packages/tgui/interfaces/FlockPanel.js
Labels: bug, tgui, size/XS

#34 Added a drone resource display and moved some HUD elements around to make room
  code/datums/abilities/flockdrone.dm
  code/datums/hud/flockdrone.dm
  code/mob/living/critter/flock/flockdrone.dm
  goonstation.dme
Labels: QoL, size/M

#51 Flockdrones now glow
  code/mob/living/critter/flock/flockdrone.dm
Labels: feature, size/XS, QoL

#33 Flock Compute Base
  code/datums/abilities/flock/flockmind.dm
  code/datums/flock/flock.dm
  code/datums/flock/flocktilegroup.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/critter/flockcritter_parent.dm
  code/mob/living/intangible/flock/flockmind.dm
  code/mob/living/intangible/flock/flocktrace.dm
  code/mob/living/intangible/flockmob_parent.dm
  code/obj/flock/structure/collector.dm
  code/obj/flock/structure/egg.dm
  code/obj/flock/structure/flock_structure_parent.dm
  code/obj/flock/structure/rift.dm
  code/obj/flock/structure/sentinel.dm
  code/turf/turf_flock.dm
Labels: size/L

#56 Prevent cancelling Fabricate Structure ability from applying the ability cooldown
  code/datums/abilities/flock/flockmind.dm
Labels: bug, size/XS

#50 Fix using Concentrated Repair Burst ability on drones with full health
  code/datums/abilities/flock/flockmind.dm
Labels: bug, size/XS

#55 Give Flockmind and Flocktrace layers
  code/mob/living/intangible/flock/flockmind.dm
  code/mob/living/intangible/flock/flocktrace.dm
Labels: size/XS

#49 Fix designating as enemy things that shouldn't be designated using the Designate Enemy ability.
  code/datums/abilities/flock/flockmind.dm
Labels: bug, size/S

#37 Added ways to cancel tealprints
  browserassets/tgui/tgui.bundle.css
  browserassets/tgui/tgui.bundle.js
  code/datums/flock/flock.dm
  code/obj/flock/structure/flock_structure_ghost.dm
  tgui/packages/tgui/interfaces/FlockPanel.js
Labels: tgui, feature, QoL, size/M

#57 Prevent creating tealprints on tiles that have something with density
  code/datums/abilities/flock/flockmind.dm
Labels: size/XS

#60 Anchor Flockmind rift
  code/obj/flock/structure/rift.dm
Labels: feature, size/XS

#54 Restrict Flockmind rift placement
  code/datums/abilities/flock/flockmind.dm
Labels: size/M

#65 Remove flockbits from panel
  browserassets/tgui/tgui.bundle.js
  code/datums/flock/flock.dm
  tgui/packages/tgui/interfaces/FlockPanel.js
Labels: bug, tgui, size/XS

#70 Allow Designate Enemy ability to undesignate enemies
  code/datums/abilities/flock/flockmind.dm
Labels: feature, QoL, size/S

#73 Makes flock using announcement computers come out garbled
  code/obj/machinery/computer/announcement.dm
Labels: bug, size/XS

#76 Update name tags for living Flock
  code/mob/living/critter/flock/flockbit.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/intangible/flock/flockmind.dm
  code/mob/living/intangible/flock/flocktrace.dm
Labels: bug, feature, size/XS

#62 Allows flockdrones to convert human computers
  browserassets/tgui/tgui.bundle.js
  code/WorkInProgress/computerx/peripherals.dm
  code/datums/flock/flock.dm
  code/modules/networks/computer3/peripherals.dm
  code/obj/flock/structure/collector.dm
  code/obj/flock/structure/compute.dm
  code/obj/flock/structure/flock_structure_parent.dm
  code/obj/flock/structure/rift.dm
  code/obj/flock/structure/sentinel.dm
  goonstation.dme
  icons/misc/featherzone.dmi
  tgui/packages/tgui/interfaces/FlockPanel.js
Labels: tgui, feature, sprites, size/M

#82 Fix not being able to designate space tiles
  code/datums/abilities/flock/flockmind.dm
  code/datums/flock/flock.dm
Labels: bug, size/XS

#81 Fix catwalk conversion
  code/datums/flock/flock.dm
Labels: bug, size/M

#83 Fix depositing resources to a tealprint when you have none
  code/mob/living/critter/flock/flockdrone.dm
Labels: bug, size/XS

#86 Fix shooting Flockdrones not designating you as an enemy
  code/mob/living/critter/flock/flockdrone.dm
Labels: bug, size/XS

#90 Fix missing barricade sprite
  icons/misc/featherzone.dmi
Labels: bug, size/XS, sprites

#84 Fix Flockdrone possession showing wrong intent on HUD
  code/mob/living/critter/flock/flockdrone.dm
Labels: bug, size/XS

#91 Fix putting grabs in the disintegration reclaimer
  code/mob/living/critter/flock/flockdrone.dm
Labels: bug, size/S

#93 Fix cancelling Flockdrone tile conversion not removing overlay
  code/mob/living/critter/flockcritter_parent.dm
Labels: bug, size/XS

#95 Fixed multiple flockdrones butchering the same corpse
  code/datums/controllers/action_controls.dm
  code/mob/living/critter.dm
  code/mob/living/critter/ai/flock/flocktasks.dm
Labels: QoL, size/S

#77 Allow structures to give a SYSTEM message on the Flock channel
  code/obj/flock/structure/flock_structure_ghost.dm
  code/procs/mobprocs/chatprocs.dm
Labels: feature, size/M

#96 Add Flock protection component
  code/datums/flock/flockprotection.dm
  goonstation.dme
Labels: size/M

#94 Prevents flockminds from teleporting to deleted drones
  code/mob/living/intangible/flock/flockmind.dm
Labels: size/XS

#101 Prevent Flock floor tiles from being burned
  code/turf/turf_flock.dm
Labels: bug, size/XS

#99 Fix Flock floor tile sounds not playing
  code/turf/turf_flock.dm
Labels: bug, size/XS

#98 Fill missing pixels in fibrenet sprite
  icons/misc/featherzone.dmi
Labels: size/XS, sprites
