Repository stonepillars/goon-flock, pull requests merged in 2022-04, with the labels that each got.

#100 Fix being able to fling Flock floor tiles
  code/modules/items/specials/ItemSpecials.dm
Labels: bug, size/XS

#118 Flock relay now renders over everything
  code/obj/flock/structure/relay.dm
Labels: bug, size/XS

#111 changes flock critter blood to gnesis
  code/mob/living/critter/flockcritter_parent.dm
Labels: size/XS

#113 add special handling for card_groups
  code/mob/living/critter/ai/flock/flocktasks.dm
Labels: size/XS

#121 Use tgui prompt for destroying a Flocktrace
  code/datums/flock/flock.dm
Labels: size/XS

#120 Bring ghost Flocktrace offer up to date with other offers
  code/datums/abilities/flock/flockmind.dm
  code/mob/living/intangible/flock/flockmind.dm
  code/mob/transform_procs.dm
Labels: size/M

#122 Fixed flockminds not being able to use certain hotkeys
  code/mob/living/intangible/flockmob_parent.dm
Labels: bug, size/XS

#106 Add some more system integrity messages
  code/obj/flock/cage.dm
  code/obj/flock/furniture.dm
Labels: size/XS

#107 Fix cage health
  code/obj/flock/cage.dm
Labels: bug, size/XS

#109 Improve hit feedback for cages
  code/obj/flock/cage.dm
Labels: size/S

#116 Fix creating barricades on tiles they shouldn't be able to be made on
  code/mob/living/critter/flock/flockdrone.dm
Labels: bug, size/S

#115 Add Flockcloset attackby restrictions
  code/obj/flock/furniture.dm
Labels: bug, size/M

#119 Change how Flockwalls are deconstructed
  code/mob/living/critter/flockcritter_parent.dm
  code/turf/turf_flock.dm
Labels: feature, size/XS

#63 Unlockable Flock Structures! Also Endgame!
  code/datums/abilities/flock/flockmind.dm
  code/datums/flock/flock.dm
  code/datums/flock/flockunlockable.dm
  code/obj/flock/structure/collector.dm
  code/obj/flock/structure/flock_structure_ghost.dm
  code/obj/flock/structure/flock_structure_parent.dm
  code/obj/flock/structure/relay.dm
  code/obj/flock/structure/sentinel.dm
  goonstation.dme
Labels: feature, size/L

#89 Prevent Flock stuff from being harmed by Flockdrones
  code/datums/flock/flockprotection.dm
  code/mob/living/critter/flock/flockbit.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/obj/flock/cage.dm
  code/obj/flock/furniture.dm
  code/obj/flock/structure/flock_structure_parent.dm
  code/obj/machinery/door/feather.dm
  code/obj/window.dm
  code/turf/turf_flock.dm
Labels: bug, feature, size/M

#108 Fix Flock stuff having no attack delay
  code/obj/flock/cage.dm
  code/obj/flock/structure/flock_structure_parent.dm
  code/turf/turf_flock.dm
Labels: bug, size/XS

#125 Allow Flockdrone incapacitor to point blank
  code/mob/living/critter/flock/flockdrone.dm
Labels: feature, size/S

#114 Prevent blocking from shocking Flockdrones
  code/mob/living/critter/flock/flockdrone.dm
Labels: bug, size/S

#97 Allow Flock structures to report when attacked
  code/obj/flock/structure/flock_structure_parent.dm
Labels: feature, size/S

#130 Fix flocktraces dying at 100 compute
  code/mob/living/intangible/flock/flocktrace.dm
Labels: bug, size/XS

#129 Add flock control panel to abilities after rift spawn
  code/datums/abilities/flock/flockmind.dm
  code/mob/living/intangible/flock/flockmind.dm
Labels: size/XS

#131 Flockdrone projectile buff
  code/mob/living/critter/flock/flockdrone.dm
Labels: size/XS

#128 Fix being able to heal Flockdrones with wires and welding tools
  code/mob/living/critter/flockcritter_parent.dm
Labels: bug, size/S

#112 Fixes a couple issues with items being awkward
  code/mob/living/critter/ai/flock/flocktasks.dm
Labels: size/M

#133 Flock victory destroys all radios
  code/obj/flock/structure/relay.dm
  code/obj/item/device/radio.dm
  code/procs/mobprocs/chatprocs.dm
Labels: feature, size/M

#134 Makes flockdrone density work properly
  code/mob/living/critter/flock/flockdrone.dm
Labels: size/S

#102 Allow for Flockwalls to be breakable
  code/obj/item/grenades.dm
  code/turf/turf_flock.dm
Labels: feature, size/L

#145 Fix Flockcloset runtime when closing over another closet
  code/obj/flock/furniture.dm
Labels: size/XS, runtime

#146 Fixes AI drones not being able to attack
  code/mob/living/critter/ai/flock/flocktasks.dm
Labels: bug, size/XS

#142 Disallow broken walls from reflecting energy projectiles
  code/turf/turf_flock.dm
Labels: feature, size/XS

#152 Prevent buckling of Flockdrones and Flockbits
  code/obj/stool.dm
Labels: size/XS

#151 Make minor Flock structure attack adjustments/improvements
  code/obj/flock/structure/flock_structure_parent.dm
Labels: size/S

#148 Mark people who throw objects at Flockdrones as enemies
  code/mob/living/critter/flock/flockdrone.dm
Labels: feature, size/XS

#154 Prevent Flockdrones from entering vehicles
  code/modules/transport/pods/vehicle.dm
Labels: bug, size/XS

#150 Prevent setting signals for Flockdoors with multitools
  code/obj/machinery/door/feather.dm
Labels: bug, size/XS

#126 Flock AI Tweaks 2: Electric Boogaloo
  browserassets/tgui/tgui.bundle.js
  code/datums/controllers/process/mob_ai.dm
  code/datums/flock/flock.dm
  code/mob/living/critter/ai.dm
  code/mob/living/critter/ai/flock/flockdrone.dm
  code/mob/living/critter/ai/flock/flocktasks.dm
  code/mob/living/critter/ai/shared.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/critter/flockcritter_parent.dm
  tgui/packages/tgui/interfaces/FlockPanel.js
Labels: tgui, size/L

#147 Give Flockdrones and Flockbits radiation immunity
  code/mob/living/critter/flockcritter_parent.dm
Labels: size/XS

#159 Add floor light sprite and fix flock conversion double converting
  code/datums/flock/flock.dm
  code/obj/flock/furniture.dm
  icons/obj/lighting.dmi
Labels: sprites, size/M

#123 Cage all the things
  code/datums/abilities/flock/flockmind.dm
  code/datums/flock/flock.dm
  code/mob/living/critter/ai/flock/flocktasks.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/critter/flockcritter_parent.dm
  code/obj/flock/cage.dm
  code/obj/flock/structure/flock_structure_parent.dm
Labels: size/L

#166 Prevent diffracting dead drones
  code/datums/abilities/flock/flockmind.dm
Labels: bug, size/S

#172 End floorrunning when ejecting from a drone
  code/mob/living/critter/flock/flockdrone.dm
Labels: bug, size/XS

#179 fixes runtime on difract in space
  code/mob/living/critter/flock/flockdrone.dm
Labels: size/XS

#165 Light icon fixes
  code/obj/flock/furniture.dm
  icons/obj/lighting.dmi
Labels: size/XS, sprites

#143 Change Flockmind death condition
  code/mob/living/intangible/flock/flockmind.dm
  code/obj/flock/structure/egg.dm
  code/obj/flock/structure/rift.dm
Labels: bug, size/S

#135 Flocktrace abilities (ping)
  browserassets/css/browserOutput.css
  code/datums/abilities/flock/flockmind.dm
  code/datums/flock/flock.dm
  code/mob/living/intangible/flock/flockmind.dm
  code/mob/living/intangible/flock/flocktrace.dm
  code/mob/living/intangible/flockmob_parent.dm
  icons/mob/flock_ui.dmi
  sound/misc/flockmind/ping.ogg
Labels: feature, sprites, size/L, sound

#185 Flockdrones can now eat bells
  code/mob/living/critter/ai/flock/flocktasks.dm
Labels: bug, size/XS

#184 Fix some Flockdrone healing bugs
  code/datums/abilities/flock/flockmind.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/critter/flockcritter_parent.dm
Labels: bug, size/S

#186 Fix Flockdrone system integrity showing to be less than 0%
  code/mob/living/critter/flock/flockbit.dm
  code/mob/living/critter/flock/flockdrone.dm
Labels: bug, size/XS

#187 Adds a tick() call to interrupt
  code/mob/living/critter/ai.dm
Labels: size/XS

#191 Add ability cooldowns
  code/datums/abilities/flock/flockmind.dm
Labels: feature, size/XS

#189 Prevent damaging Flock stuff with incapacitor
  code/mob/living/critter/flock/flockbit.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/obj/flock/furniture.dm
  code/obj/flock/structure/flock_structure_parent.dm
  code/obj/machinery/door/feather.dm
Labels: feature, size/S

#193 Fixes flockmind being unable to act while partitioning
  code/datums/abilities/flock/flockmind.dm
  code/mob/living/intangible/flock/flockmind.dm
Labels: QoL, size/S

#192 Adds flock cheatmode admin verb
  code/datums/flock/flock.dm
  code/datums/flock/flockunlockable.dm
  code/modules/admin/admin_verbs.dm
Labels: QoL, size/M

#198 atom property on things
  _std/macros/atom_properties.dm
  code/datums/flock/flock.dm
Labels: feature, size/XS

#200 Centre the light sprite properly
  icons/obj/lighting.dmi
Labels: size/XS, sprites

#139 Tile designation fix
  code/datums/flock/flock.dm
Labels: size/S

#188 Adds bounds checking to large flock structures, plus ability to deconstruct flock stuff to clear space
  code/datums/abilities/flock/flockmind.dm
  code/datums/flock/flock.dm
  code/datums/flock/flockunlockable.dm
  code/mob/living/critter/ai/flock/flockdrone.dm
  code/mob/living/critter/ai/flock/flocktasks.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/critter/flockcritter_parent.dm
  code/mob/living/intangible/flock/flockmind.dm
  code/obj/flock/structure/flock_structure_ghost.dm
  code/obj/flock/structure/flock_structure_parent.dm
Labels: bug, feature, size/L

#194 Add cost to floorrunning
  code/mob/living/critter/flock/flockdrone.dm
  code/turf/turf_flock.dm
Labels: feature, size/S

#205 Add toggleable deconstruction
  code/datums/abilities/flock/flockmind.dm
  code/datums/flock/flock.dm
  code/mob/living/critter/ai/flock/flocktasks.dm
Labels: size/S

#163 Flock protection comp blah
  _std/defines/component_defines.dm
  code/datums/flock/flock.dm
  code/datums/flock/flockprotection.dm
  code/mob/living/critter/flock/flockbit.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/obj/flock/furniture.dm
  code/obj/flock/structure/flock_structure_parent.dm
  code/obj/machinery/door/feather.dm
  code/obj/window.dm
  code/turf/turf_flock.dm
Labels: weird, size/L

#209 Adds icon for flock deconstruction ability
  code/datums/abilities/flock/flockmind.dm
  code/mob/living/critter/flockcritter_parent.dm
  icons/mob/flock_ui.dmi
Labels: size/XS, sprites

#138 Flock antag popups
  _std/macros/antag_popups.dm
  browserassets/html/traitorTips/flockmindTips.html
  browserassets/html/traitorTips/flocktraceTips.html
  browserassets/images/antagTips/flockmind.gif
  browserassets/images/antagTips/flocktrace.gif
  code/mob/transform_procs.dm
Labels: feature, size/M

#207 Add Flock atom property to Flock structures
  code/mob/living/critter/flock/flockdrone.dm
  code/obj/flock/structure/flock_structure_parent.dm
Labels: bug, size/XS

#183 Make every health-based Flock thing repairable
  code/datums/flock/flock.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/critter/flockcritter_parent.dm
  code/obj/flock/furniture.dm
  code/obj/flock/structure/flock_structure_parent.dm
  code/obj/machinery/door/feather.dm
  code/obj/window.dm
  code/turf/turf_flock.dm
Labels: feature, size/L

#180 Flockdrones stare at birds occasionally
  code/mob/living/critter/ai/flock/flockdrone.dm
  code/mob/living/critter/ai/flock/flocktasks.dm
  code/mob/living/critter/flock/flockdrone.dm
Labels: size/M

#212 Remove Flock critters that leave the station z level from their Flock
  code/mob/living/critter/flock/flockbit.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/intangible/flock/flockmind.dm
  code/mob/living/intangible/flockmob_parent.dm
  icons/misc/featherzone.dmi
Labels: feature, sprites, size/M

#92 Fix floorrunning bugs
  code/atom.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/turf/turf_flock.dm
Labels: bug, size/L

#214 Adds flockpanel icons for observing and deconstructing
  browserassets/tgui/tgui.bundle.css
  browserassets/tgui/tgui.bundle.js
  tgui/packages/tgui/interfaces/FlockPanel.js
Labels: bug, tgui, size/XS

#213 Moves the target reset from sequence to aiTask
  code/mob/living/critter/ai.dm
  code/mob/living/critter/ai/shared.dm
Labels: bug, size/XS

#110 Gnesis turret
  code/datums/abilities/flock/flockmind.dm
  code/datums/flock/flockunlockable.dm
  code/obj/flock/cage.dm
  code/obj/flock/structure/gnesisturret.dm
  goonstation.dme
Labels: size/L

#181 Flockdrone menu
  code/datums/abilities/flock/flockmind.dm
  code/mob/living/critter/ai.dm
  code/mob/living/critter/ai/flock/flock_common.dm
  code/mob/living/critter/ai/flock/flocktasks.dm
  code/mob/living/critter/ai/ocean.dm
  code/mob/living/critter/ai/shared.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/intangible/flockmob_parent.dm
  code/modules/interface/multiContext/context_actions.dm
  code/modules/interface/multiContext/context_layouts.dm
  code/modules/interface/multiContext/multiContext.dm
  icons/ui/context16x16.dmi
Labels: feature, sprites, size/L, QoL

#217 Make ghost structures drop a resource cube on destruction instead of scrap
  code/obj/flock/structure/flock_structure_ghost.dm
Labels: size/XS

#216 Fix walls by created and destroyed Flockdoors not updating properly
  code/obj/machinery/door/feather.dm
Labels: bug, size/XS

#223 Change color for Flock depositing after first deposit
  code/mob/living/critter/flockcritter_parent.dm
Labels: size/XS

#222 Prevent drones from reporting dormancy on deletion
  code/mob/living/critter/flock/flockdrone.dm
Labels: bug, size/XS

#224 Fix being able to use cargo teleporters on Flock closets
  code/obj/mining.dm
Labels: bug, size/XS

#232 very important
  code/modules/admin/admin.dm
Labels: size/XS

#230 Standardize material across Flock stuff
  code/mob/living/critter/flockcritter_parent.dm
  code/obj/flock/furniture.dm
  code/obj/flock/structure/flock_structure_parent.dm
  code/obj/machinery/door/feather.dm
  code/obj/window.dm
  code/turf/turf_flock.dm
Labels: bug, feature, size/M

#221 Add proper disposing for Flockdrones and Flockbits
  code/mob/living/critter/flock/flockbit.dm
  code/mob/living/critter/flock/flockdrone.dm
Labels: bug, size/M
