Repository stonepillars/goon-flock, pull requests merged in 2022-05, with the labels that each got.

#245 shut up you stupid birds
  code/datums/flock/flock.dm
  code/mob/living/critter/flock/flockbit.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/critter/flockcritter_parent.dm
  code/obj/flock/structure/flock_structure_ghost.dm
  code/obj/flock/structure/flock_structure_parent.dm
Labels: size/M

#197 Change how annotations are updated
  code/datums/abilities/flock/flockmind.dm
  code/datums/flock/flock.dm
  code/mob/living/critter/ai/flock/flocktasks.dm
  code/mob/living/critter/flock/flockdrone.dm
Labels: size/L

#252 Fix rallying over long distances
  code/mob/living/critter/ai/shared.dm
Labels: size/XS

#254 Stop animation when stuff is taken out of the absorber
  code/mob/living/critter.dm
  code/mob/living/critter/flock/flockdrone.dm
Labels: size/XS

#249 Make flocktraces be antags
  _std/defines/roles.dm
  code/mob/living/intangible/flock/flocktrace.dm
  code/mob/transform_procs.dm
Labels: size/XS

#243 Add Flockmind promotion framework
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/intangible/flock/flockmind.dm
  code/mob/living/intangible/flock/flocktrace.dm
Labels: feature, size/M

#255 Make visibility changes for Flock
  _std/defines/invisibility.dm
  code/datums/flock/flock.dm
  code/mob/living/critter/flockcritter_parent.dm
  code/mob/living/intangible/flockmob_parent.dm
  code/mob/living/life/sight.dm
Labels: bug, feature, size/S

#246 Flock relay now blocks shuttle calls and recalls the shuttle if it is in transit
  code/obj/flock/structure/relay.dm
Labels: feature, size/S, balance

#250 Allow drones to attack pods
  _std/macros/vehicles.dm
  code/datums/abilities/flock/flockmind.dm
  code/datums/flock/flock.dm
  code/mob/living/critter/ai/flock/flocktasks.dm
  code/mob/living/critter/flock/flockdrone.dm
Labels: bug, size/M

#256 Make Flockwalls only be on when a Flockdrone is floorrunning through them
  code/mob/living/critter/flock/flockdrone.dm
  code/turf/turf_flock.dm
  icons/misc/featherzone.dmi
Labels: sprites, size/M

#263 Cuts relay charge time to 6 minutes and adds a crew announcement for it
  code/obj/flock/structure/relay.dm
Labels: size/XS, balance

#260 Prevent flockdrones from admin messaging on attack after spawning
  code/mob/living/critter/flock/flockdrone.dm
Labels: size/XS

#258 Make Flockdrone abilities unresumable
  code/mob/living/critter/flockcritter_parent.dm
Labels: bug, size/XS

#259 Fixes drones still moving when controlled
  code/mob/living/critter/ai.dm
  code/mob/living/critter/ai/shared.dm
  code/mob/living/critter/flock/flockbit.dm
  code/mob/living/critter/flock/flockdrone.dm
Labels: bug, size/XS

#265 quick fix to not move bits onto dense tiles
  code/mob/living/critter/flock/flockdrone.dm
Labels: size/XS

#206 Flock protection comp blah
  _std/defines/component_defines.dm
  code/datums/flock/flock.dm
  code/datums/flock/flockprotection.dm
  code/mob/living/critter/flock/flockbit.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/obj/flock/furniture.dm
  code/obj/flock/structure/flock_structure_parent.dm
  code/obj/machinery/door/feather.dm
  code/obj/window.dm
  code/turf/turf_flock.dm
Labels: size/L

#267 Move shared Flock critter stuff to parent procs
  code/mob/living/critter/flock/flockbit.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/critter/flockcritter_parent.dm
Labels: size/M

#268 Flock walls in 3/4
  code/datums/flock/flock.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/critter/flockcritter_parent.dm
  code/obj/flock/trader.dm
  code/obj/window.dm
  code/turf/turf_flock.dm
  icons/turf/walls_flock.dmi
Labels: sprites, size/M

#273 Fix bad icon state for spawn-wall sprite
  icons/misc/featherzone.dmi
Labels: size/XS, sprites

#264 Prevents beepsky from opening featherdoors
  _std/pathfinding.dm
  code/obj/machinery/door/door_parent.dm
  code/obj/machinery/door/feather.dm
Labels: bug, size/XS

#277 Fix runtimes while checking for disposed busy stuff
  code/datums/flock/flock.dm
Labels: size/XS, runtime

#276 Drone control icons
  code/datums/flock/flock.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/intangible/flock/flockmind.dm
  code/mob/living/intangible/flock/flocktrace.dm
  code/mob/living/intangible/flockmob_parent.dm
  icons/misc/featherzone.dmi
Labels: feature, sprites, size/M

#279 More anim fixes
  code/datums/critter_mobs/equipment.dm
  code/mob/living/critter/ai/flock/flocktasks.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/modules/materials/Mat_ProcsDefines.dm
Labels: size/M

#281 whoopsie
  code/obj/window.dm
Labels: size/XS

#275 Restrict some Flock stuff from being marked for deconstruction or deconstructed
  _std/macros/flock.dm
  code/datums/abilities/flock/flockmind.dm
  code/mob/living/critter/flock/flockdrone.dm
Labels: bug, size/S

#280 Flock gamemode work
  code/datums/flock/flock.dm
  code/datums/gamemodes/flock.dm
  code/datums/gamemodes/gm_parent.dm
  code/datums/objective.dm
  code/mob/living/intangible/flock/flocktrace.dm
  code/mob/transform_procs.dm
  code/obj/flock/structure/relay.dm
Labels: feature, size/M

#274 Fix not being able to convert Flock lattices to floors
  code/mob/living/critter/flock/flockdrone.dm
Labels: bug, size/S

#283 Better wandering
  code/mob/living/critter/ai/flock/flockdrone.dm
  code/mob/living/critter/ai/flock/flocktasks.dm
  code/mob/living/critter/ai/shared.dm
Labels: size/M

#287 Flockdrone/bits no longer metabolise chems
  code/mob/living/critter/flockcritter_parent.dm
Labels: size/XS

#61 Prevent Flockdrones and Flockbits from being moved by conveyors and drivers
  code/WorkInProgress/recycling/conveyor.dm
  code/obj/machinery/launcherloader.dm
  code/obj/machinery/mass_driver.dm
Labels: feature, size/S, Certified Organic

#253 Give Flockdrones and Flockbits health icons
  code/datums/flock/flock.dm
  code/mob/living/critter/flock/flockbit.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/critter/flockcritter_parent.dm
  icons/misc/featherzone.dmi
Labels: feature, sprites, size/M

#296 fix #291
  code/obj/flock/structure/relay.dm
Labels: size/XS

#297 Makes pinging turfs a little less weird
  code/datums/flock/flock.dm
Labels: size/XS

#270 Rework and improve item absorption
  code/mob/living/critter/flock/flockdrone.dm
  code/obj/item.dm
Labels: size/L

#292 Add flock parameter to Flock mass conversion procs
  code/datums/flock/flock.dm
  code/obj/flock/structure/relay.dm
Labels: bug, size/S

#289 Efficient AI please
  code/mob/living/critter/ai/flock/flocktasks.dm
  code/mob/living/critter/ai/shared.dm
  code/obj/flock/cage.dm
  code/obj/flock/structure/flock_structure_ghost.dm
  code/procs/helpers.dm
Labels: size/L

#298 Fixes very threatening walls
  code/datums/flock/flockprotection.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/critter/flockcritter_parent.dm
Labels: bug, size/S

#288 Flock annotations refactor
  _std/macros/flock.dm
  code/datums/flock/flock.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/critter/flockcritter_parent.dm
  code/mob/living/intangible/flock/flockmind.dm
  code/mob/living/intangible/flock/flocktrace.dm
  code/mob/living/intangible/flockmob_parent.dm
Labels: size/L, cleanliness

#293 Fix some dormancy bugs
  code/mob/living/critter/flock/flockbit.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/critter/flockcritter_parent.dm
  code/mob/living/intangible/flockmob_parent.dm
Labels: bug, size/M

#299 Minor balance change
  code/mob/living/critter/ai/flock/flocktasks.dm
  code/mob/living/critter/flock/flockdrone.dm
Labels: size/XS

#301 Fixed some flockdrone absorber jank and nerfed paperbin health
  code/mob/living/critter/flock/flockdrone.dm
  code/obj/item/paper.dm
Labels: bug, size/XS

#290 Properly handle Flockmind and Flocktrace suicides
  code/datums/flock/flock.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/intangible/flock/flockmind.dm
  code/mob/living/intangible/flock/flocktrace.dm
  code/mob/suicide.dm
  code/obj/flock/structure/rift.dm
Labels: bug, size/M

#302 Lets the flock convert the mainframe
  code/datums/flock/flock.dm
  code/obj/flock/structure/compute.dm
  icons/misc/featherzone.dmi
Labels: feature, size/XS, sprites

#300 Make complexDroneCount() not stupid.
  code/datums/flock/flock.dm
  code/mob/living/critter/flock/flockdrone.dm
Labels: size/M

#199 Prevent multiple of the same name from being given to Flock entities
  code/datums/flock/flock.dm
  code/mob/living/critter/flock/flockbit.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/intangible/flock/flocktrace.dm
Labels: bug, feature, size/M

#304 Fixes deleted enemies causing runtimes
  code/datums/flock/flock.dm
Labels: bug, size/XS

#294 Basic cleanup
  _std/macros/flock.dm
  code/datums/abilities/flock/flockmind.dm
  code/datums/flock/flock.dm
  code/mob/living/critter/ai/flock/flocktasks.dm
  code/mob/living/critter/flock/flockbit.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/critter/flockcritter_parent.dm
  code/mob/living/intangible/flock/flockmind.dm
  code/mob/living/intangible/flock/flocktrace.dm
  code/obj/flock/cage.dm
  code/obj/flock/furniture.dm
  code/obj/flock/goods.dm
  code/obj/flock/structure/collector.dm
  code/obj/flock/structure/egg.dm
  code/obj/flock/structure/flock_structure_ghost.dm
  code/obj/flock/structure/flock_structure_parent.dm
  code/obj/flock/structure/relay.dm
  code/obj/flock/structure/rift.dm
  code/obj/item/device/radio.dm
  code/obj/item/organs/brain.dm
  code/obj/item/organs/heart.dm
  code/obj/machinery/door/feather.dm
  code/obj/window.dm
  code/turf/turf_flock.dm
Labels: size/XXL

#313 Added ping sound file to sound cache
  code/datums/flock/flock.dm
  code/modules/sound/soundCache.dm
Labels: size/XS, cleanliness

#312 you need FLOCK
  code/mob/living/critter/flock/flockdrone.dm
Labels: size/XS

#310 fix race condition with paper bins
  code/mob/living/critter/ai/flock/flocktasks.dm
Labels: size/XS

#305 Flock control panel now only sends relevent data
  browserassets/tgui/tgui.bundle.css
  browserassets/tgui/tgui.bundle.js
  code/datums/flock/flock.dm
  tgui/packages/tgui/interfaces/FlockPanel.js
Labels: tgui, size/L, cleanliness

#311 gib structures on suicide
  code/datums/flock/flock.dm
Labels: size/XS

#320 Lets admins spawn flock rift in space
  code/datums/abilities/flock/flockmind.dm
Labels: bug, size/XS

#318 Adjusted some ability timings
  code/datums/abilities/flock/flockmind.dm
Labels: size/XS, cleanliness

#317 Feedback on casting abilities on dead drones
  code/datums/abilities/flock/flockmind.dm
Labels: bug, size/XS

#315 Refactors pathing and featherdoor access
  _std/pathfinding.dm
  code/obj/machinery/door/door_parent.dm
  code/obj/machinery/door/feather.dm
Labels: size/S, cleanliness

#314 assoc list gud
  code/datums/abilities/flock/flockmind.dm
Labels: size/XS

#319 Defines flockdrones as restrained while floorrunning
  code/atom.dm
  code/mob/living/critter/flock/flockdrone.dm
Labels: bug, size/S

#316 Renames isflock to isflockmob
  _std/macros/flock.dm
  code/WorkInProgress/recycling/conveyor.dm
  code/datums/abilities/flock/flockmind.dm
  code/datums/flock/flock.dm
  code/mob/living/critter/ai/flock/flocktasks.dm
  code/mob/living/critter/flock/flockbit.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/intangible/flock/flockmind.dm
  code/mob/living/intangible/flock/flocktrace.dm
  code/modules/admin/player_options.dm
  code/modules/transport/pods/vehicle.dm
  code/obj/flock/cage.dm
  code/obj/flock/furniture.dm
  code/obj/flock/goods.dm
  code/obj/flock/structure/flock_structure_parent.dm
  code/obj/flock/structure/gnesisturret.dm
  code/obj/flock/structure/sentinel.dm
  code/obj/flock/trader.dm
  code/obj/item/device/radio.dm
  code/obj/item/organs/brain.dm
  code/obj/item/organs/heart.dm
  code/obj/machinery/computer/announcement.dm
  code/obj/machinery/door/feather.dm
  code/obj/machinery/launcherloader.dm
  code/obj/machinery/mass_driver.dm
  code/obj/stool.dm
  code/obj/window.dm
  code/procs/helpers.dm
  code/procs/mobprocs/chatprocs.dm
  code/turf/turf_flock.dm
Labels: size/L, cleanliness

#322 Removed some unused procs in flock gamemode datum
  code/datums/gamemodes/flock.dm
Labels: size/XS

#324 Azrun Code Review - Achievements
  _std/macros/flock.dm
  code/datums/flock/flock.dm
  code/datums/flock/flockunlockable.dm
  code/modules/admin/admin_verbs.dm
  code/obj/flock/cage.dm
Labels: size/S

#326 Ternaries bad, || good
  code/mob/living/intangible/flock/flockmind.dm
Labels: size/XS, cleanliness

#323 Show Flockbits to be aware when possessed in their cognition description
  code/mob/living/critter/flock/flockbit.dm
Labels: feature, size/XS

#325 Fixes a corner case that will probably never occur
  code/mob/living/critter/flockcritter_parent.dm
Labels: size/XS, cleanliness

#321 Fixes some grab jank
  code/mob/living/critter/flock/flockdrone.dm
  code/turf/turf_flock.dm
Labels: bug, size/M

#330 Added copyright message to flockpanel
  tgui/packages/tgui/interfaces/FlockPanel.js
Labels: tgui, size/XS

#331 Made a comment better
  code/datums/flock/flock.dm
Labels: size/XS, cleanliness

#327 Remove gnesis girder deconstruct code
  code/datums/abilities/flock/flockmind.dm
  code/mob/living/critter/flock/flockdrone.dm
Labels: size/S

#329 Moved flock components into components folder
  code/datums/components/flock/flockprotection.dm
  code/datums/components/flock/ping.dm
  code/datums/flock/flock.dm
  code/obj/flock/structure/flock_structure_ghost.dm
  goonstation.dme
Labels: size/L, cleanliness

#333 Aloe Review 2
  code/obj/flock/cage.dm
  code/obj/flock/structure/collector.dm
  code/obj/flock/structure/gnesisturret.dm
Labels: size/S

#335 Switches mass driver to use floating atom prop
  code/obj/machinery/mass_driver.dm
Labels: size/XS, cleanliness

#334 Revert nerfs to flockdrone absorption
  code/mob/living/critter/flock/flockdrone.dm
  code/obj/flock/structure/egg.dm
  code/obj/flock/structure/rift.dm
Labels: size/S, balance

#338 Cage + Turret Cost Balance
  code/obj/flock/cage.dm
  code/obj/flock/structure/gnesisturret.dm
  code/obj/flock/structure/sentinel.dm
  code/obj/machinery/door/feather.dm
Labels: size/S

#336 Allow flock to work as a random event antag
  code/datums/flock/flock.dm
  code/datums/gamemodes/flock.dm
  code/datums/objective.dm
  code/modules/events/antag_ghost_respawn.dm
  code/obj/flock/structure/relay.dm
Labels: bug, size/S

#339 Anti-birdwatching balance
  code/datums/flock/flock.dm
  code/mob/living/critter/flockcritter_parent.dm
  code/mob/living/intangible/flockmob_parent.dm
  code/obj/machinery/camera.dm
Labels: size/M, balance

#337 Added attack feedback to flock structures
  code/obj/flock/cage.dm
  code/obj/flock/structure/flock_structure_parent.dm
  code/obj/flock/structure/relay.dm
Labels: feature, size/S
